### ISSUE TITLE
PDFView is not imported by default {N} + angular (nativescript@2.5.2)

### ISSUE THREAD

**Issue by echap** [Merott/nativescript-pdf-view#15]
Hi,

Just to inform you that the `PDFView` is not correctly imported on the project, adding this snippet on `main.ts` solves the issue :

```
import {registerElement} from "nativescript-angular/element-registry";
registerElement("PDFView", () => require("nativescript-pdf-view").PDFView);

```

with nativescript@2.5.2

Cheers,

**Comment by imaginationcoder** [comment]
Still I am getting below error 

`npm run start-android-bundle`
`
Module not found: Error: Can't resolve 'nativescript-pdf-view' in '/Users/maisapride7/workspace/KIDSAPP/tingr-ns-app/app'`

and app.module.ts contains

`registerElement("PDFView", () => require("nativescript-pdf-view").PDFView);`

**Comment by Merott** [comment]
I just release version 2 of this plugin, and have removed the auto-registration of the PDFView element. It's now required to manually do so in your own applications.
