### ISSUE TITLE
Cannot make it work with angular

### ISSUE THREAD

**Issue by searleser97** [Merott/nativescript-pdf-view#17]
this is what I have

name.html
...
`<PDFView [src]="src" (load)="onLoad()"></PDFView>`
...

name.component.ts
...
```
import "nativescript-pdf-view"
...
export class nameComponent {
    src = "https://www.princexml.com/samples/flyer/flyer.pdf";
    public onLoad() {
        alert('hi');
    }
}
```
...

It's just showing the alert but not the pdf.

**Comment by Merott** [comment]
Could you please verify if this issue still exists on the newly release version 2?

**Comment by EddyVerbruggen** [comment]
You may be missing the imports mentioned in the readme:

```typescript
import { PDFView } from 'nativescript-pdf-view';
import { registerElement } from 'nativescript-angular';
registerElement('PDFView', () => PDFView);
```

And if it still doesn't appear you can try the flex layout mentioned in the readme, or as a quick check add width and height:

```html
<PDFView width="200" height="200" [src]="src" (load)="onLoad()"></PDFView>
```

**Comment by searleser97** [comment]
is good now
