### ISSUE TITLE
implementation without angular not working

### ISSUE THREAD

**Issue by stephanvermeire** [Merott/nativescript-pdf-view#2]
Hi Merrot,

This is really a great plugin! 

I have the angular demo working but I don't really know how to implement the plugin in my current non-angular project. I installed the plugin and during build phase this is confirmed:

:config phase:  createDefaultIncludeFiles
        +found plugins: nativescript-pdf-view
        +found plugins: tns-core-modules-widgets

However when I put the next code on mij xml-page:

```
<Page>
        <PDFView src="'http://www.pdf995.com/samples/pdf.pdf'"></PDFView>
</Page>
```

I get the following error when I hit the page that contains the pdfView:

`Module 'ui/p-d-f-view' not found for element PDFView`

What am I doing wrong?
Thanx, Stephan

**Comment by stephanvermeire** [comment]
My mistake, I have got the PDFView running without errors:

<Page xmlns:pdf="nativescript-pdf-view">
        <pdf:PDFView src="http://www.pdf995.com/samples/pdf.pdf"/>
</Page>

Unfortunately I ran into another problem, how can I load a local file in the demo project? Could you give an example of that?

Thanx again,
Stephan

**Comment by Merott** [comment]
Hi Stephan,

I see that you've found the issue yourself.

For local files, you need to set the source to the absolute path of the file. You can use the [`file-system`](https://docs.nativescript.org/cookbook/file-system) and [`File.path`](https://docs.nativescript.org/api-reference/classes/_file_system_.file.html) to find the path of your file on iOS or Android.

If you run into any other blockers, please open another issue. Thanks.

**Comment by stephanvermeire** [comment]
Thanx for your quick reply! I have the local files running now.

**Comment by satheeshsri** [comment]
Hi stephan,

I'm trying to open a pdf from local file with Angular, my code working in Andriod, not in IOS. I can see right path printed on  my console, but file is not loading in IOS device or emulator. For URL we need to turn on some permission in IOS, am I missing some permission setup ? Can you share your code for local files for reference?

Thank you
Satheesh
