### ISSUE TITLE
Android crashes with the 3.0.0 version

### ISSUE THREAD

**Issue by EddyVerbruggen** [Merott/nativescript-pdf-view#20]
[This constructor](https://github.com/Merott/nativescript-pdf-view/blob/0e0032568dfb446f110a6bcea0e85259fe049f1b/pdf-view.android.ts#L33) requires a second argument. I'll make a PR.

**Comment by EddyVerbruggen** [comment]
See PR #21

**Comment by Merott** [comment]
Thank you @EddyVerbruggen.

I had to take your commit and change it slightly in order to pass linting, and the semantic-release commit message format. I've kept you as the author 👍.

I've also added a [CONTRIBUTING guide](./CONTRIBUTING) guide so that feature PRs can be accepted without change.
