### ISSUE TITLE
Unable to run npm run demo.android

### ISSUE THREAD

**Issue by GianniGM** [Merott/nativescript-pdf-view#24]
After installed npm packages and run  

`npm run demo.android`

i get this issue

> Unable to apply changes on device: emulator-5554. Error is: Processing node_modules failed. Error: cp: cannot create directory '/Users/laptop/NativeScriptProjects/nativescript-pdf-view/demo/platforms/android/src/main/assets/app/tns_modules': No such file or directory.

**Comment by dgmaar** [comment]
did you find a solution for this? I'm facing the same

**Comment by GianniGM** [comment]
Yes, migrating to another technology.
I'm sorry.

**Comment by dgmaar** [comment]
@GianniGM What technology :D?

**Comment by GianniGM** [comment]
@dgmaar for now, I'm using react-native, for pdfs i use this: https://github.com/cnjon/react-native-pdf-view.

**Comment by madmas** [comment]
Should be fixed with the updated demo at https://github.com/madmas/nativescript-pdf-view/tree/master/demo
