### ISSUE TITLE
Is it possible to load excel files, Image files and document files with this plugin?

### ISSUE THREAD

**Issue by kumarandena** [Merott/nativescript-pdf-view#26]
Sorry for asking question here!

I have the requirement to load excel files, Image files and document files inside the Nativescript angular application. 

Is it possible to load mentioned files as like as pdf files? 
Of if a small workaround on this plugin will help to load mentioned documents files? If yes please suggest.

**Comment by madmas** [comment]
No, this plugin is only for PDF files. Please convert your documents to PDF first :)
