### ISSUE TITLE
Erro in Android: Cannot read property OnLoadCompleteListener

### ISSUE THREAD

**Issue by dariopellegrini** [Merott/nativescript-pdf-view#28]
Hello.
In iOS works perfectly.
In Android it I have this error:
ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'OnLoadCompleteListener' of undefined

component.ts

import { PDFView } from 'nativescript-pdf-view';
import { registerElement } from 'nativescript-angular';
registerElement('PDFView', () => PDFView);

ngOnInit() {
  this.path = "https://learn.zu.ac.ae/webapps/dur-browserCheck-bb_bb60/samples/sample.pdf"
}

onLoad() {
 console.log("Loaded")
}

component.html
<PDFView [src]="path" (load)="onLoad()"></PDFView>

**Comment by isoengas** [comment]
Same error for me :(

**Comment by dpdragnev** [comment]
Any resolution to this problem?  I am experiencing the same issue.

**Comment by dpdragnev** [comment]
ok, so I removed the platform and added it again and now I am loading the plugin correctly.

**Comment by dariopellegrini** [comment]
Confirm: tns platform remove android and then tns run android.
This will solve the problem.
