### ISSUE TITLE
Is there anyway to know when the PDF is done loading?

### ISSUE THREAD

**Issue by spstratis** [Merott/nativescript-pdf-view#3]
Just curious if there is a way to know when the PDF displaying in the component is done loading or is displaying on the screen programmatically? Main purpose for me asking this is so that I can display a loading spinner while the PDF url loads. Thanks!

**Comment by Merott** [comment]
That's definitely one of top-priority items still to be done. I'm going to need the same kind of functionality for my own app.

Implementing this should be possible with [`UIWebViewDelegate#webViewDidFinishLoad`](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIWebViewDelegate_Protocol/#//apple_ref/occ/intfm/UIWebViewDelegate/webViewDidFinishLoad:) on iOS, and [`AndroidPdfViewer#onLoad`](https://github.com/barteksc/AndroidPdfViewer#load-a-pdf-file) on Android.

I'll try to do work on it sometime this week.
