### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by it3r4-pineda** [Merott/nativescript-pdf-view#31]
I've tried using this along with the File Sytem and it doesnt seem to work
I also tried directly stating the src=""

`<pdf:PDFView height="100%" src="http://drive.google.com/file/d/1MM4drrdei-OcKBNAROmev_dPxzU5AMob/view"/>`

and it just displays a white screen.

**Comment by madmas** [comment]
Yes, it dos. Please checkout the updated demo at http://drive.google.com/file/d/1MM4drrdei-OcKBNAROmev_dPxzU5AMob/view and let me know if you still have difficulties.
