### ISSUE TITLE
Nativescript-Angular after navigating with router PdfView dont work

### ISSUE THREAD

**Issue by tomylee001001** [Merott/nativescript-pdf-view#4]
Hi,
i am usin Nativesvript-angular 2 with routing.i have 2 pages in the first page i show list of pdf and when user tap any of them i send them  my second page with "this._router.navigate(["/pdfview"]);" to show the pdf in PdfView. when my second page open i set my pdfview "src" but nothing happens.it didnt show an error either , everything else work. but if i put the pdfview in my first page and anime my list with pdfview to switch them pdfview work perfeclty .

**Comment by Merott** [comment]
Would you be able to share a sample demo that reproduces the issue?

**Comment by tomylee001001** [comment]
i open demo project for this issue at https://github.com/tomylee001001/Pdfview-isuue-example
