### ISSUE TITLE
Error on Android

### ISSUE THREAD

**Issue by dpdragnev** [Merott/nativescript-pdf-view#6]
Hello,

I am trying to display a PDF file on both iOS and Android.  The iOS version looks great, however, when I load the page on an Android device, I am getting:

**Module '/data/data/com.someurl/files/app/tns_modules/nativescript-pdf-view' not found for element 'nativescript-pdf-view:PDFView'.  Cannot read property 'barteksc' of undefined**

Here is my declaration:

In the Page declaration: `xmlns:pdf="nativescript-pdf-view"`
In the markup: `<pdf:PDFView src="{{ pdfUrl }}" />`

Any idea of what I might be doing wrong?

Thank you.

**Comment by Merott** [comment]
It looks like it can't find the AndroidPdfView library, which should be installed via Gradle. Can you re-add the Android platform by running `tns platform remove android` followed by `tns platform add android`?

**Comment by dpdragnev** [comment]
This is what I thought as well, but since the iOS version, which was
deployed at the same time, works well, i thought i was doing something
wrong.

I am actually using the AppBuilder.  I added the module via Visual Studio.
I will try uninstalling the app and redeploying it again.
I will let you know if this fixed the issue.

Thank you for the quick response.

**Comment by dpdragnev** [comment]
ok, so I reinstalled the app and I am still getting the same error.  Could this be related to the fact that I am using AppBuilder?

**Comment by dpdragnev** [comment]
I can confirm that this only happens if you are using the AppBuilder.  Using VS Code and using the CLI everything works well.

I have opened a ticket with Telerik.  I suspect that this has something to do with the whitelist requirements AppBuilder has for all plugins.

I am closing this ticket, but will reopen if they come up with a solution to this problem.

Thank you.

**Comment by Merott** [comment]
Thank you for confirming this @dpdragnev

**Comment by dpdragnev** [comment]
For those using the AppBuilder, the fix is to create a file called app.gradle in app/App_Resources/Android (if you don't already have it) and in it to enter:

`dependencies {
  compile 'com.github.barteksc:android-pdf-viewer:2.0.3'
}`

Compile and you should be able run the app without a problem.
