### ISSUE TITLE
Unable to load local file in IOS

### ISSUE THREAD

**Issue by satheeshsri** [Merott/nativescript-pdf-view#7]
Hi @Merott ,

Thanks for the cool plugin. I have trouble in loading pdf file in my local, it works fine in android.  

Snippet: 

html file: 
<ScrollView>
      <PDFView [src]="loadfile" (load)="onLoad()" ></PDFView>
</ScrollView>

.ts file: 
            var documents = knownFolders.documents();
            var file: File = <File>documents.getFile("app/files/fye2016.pdf");
            this.loadfile = fs.path.normalize(file.path);
            console.log(this.loadfile);

I verified the file in simulator path and fs.file.path() returns true as well. But pdf file is never loading only on ios (simulator & device). I see below error when I access PDF file, am I missing some config in .plist? 

Error noticed on my console:

(Error) MC: MobileContainerManager gave us a path we weren't expecting; file a radar against them
    Expected:/private/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles

Thank you,
Satheesh

**Comment by Merott** [comment]
@satheeshsri 

Sorry for the long delay in getting back to you. Did you manage to get it working?

**Comment by anki247** [comment]
If someone still runs to this problem...
It is really mean that the example of @satheeshsri works on Android, which was for me really confusing.
Anyway the solution is to use `knownFolders.currentApp()` instead of `knownFolders.documents()`
````javascript
var appFolder = knownFolders.currentApp();
this.src = fs.path.join(appFolder.path, 'res_folder', 'xy.pdf');
